version: "3"

services:
  application:
    image: kiran11113/spring-boot-mysql-app
    container_name: spring-container
    ports:
      - "9090:8080"
    networks:
      - docker-mysql
    depends_on:
      - mysqldb
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb-container
    ports:
      - "3306:3306"
    networks:
      - docker-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
networks:
  docker-mysql:


